# Generated by Django 5.0.1 on 2024-01-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todolist",
            name="dueDate",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="todolist",
            name="startDate",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
