# Generated by Django 5.0.1 on 2024-01-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_todolist_duedate_alter_todolist_startdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="todolist",
            name="isComplete",
            field=models.BooleanField(default=False),
        ),
    ]
